services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${ USERNAME_POSTGRES }
      POSTGRES_USER: ${ PASSWORD_POSTGRES }
      POSTGRES_DB: todo
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      HOST_POSTGRES: ${HOST_POSTGRES}
      USERNAME_POSTGRES: ${USERNAME_POSTGRES}
      PASSWORD_POSTGRES: ${PASSWORD_POSTGRES}
    depends_on:
      - postgres

volumes:
  postgres:
