services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: process.env.PASSWORD_POSTGRES
      POSTGRES_USER: process.env.USERNAME_POSTGRES
      POSTGRES_DB: todo
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
